// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:eb90c1dc-4e6c-4a0d-b3b2-c4235792eb28',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'savethatmoney-hosting-mobilehub-634236437',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd32ere7z4k48re.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a447cec0dc1a46ada884bad67bbafee8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ffb2e8ad-2177-11e8-990e-0dddd7637768',
    'aws_project_name': 'Save_That_Money-2018-03-06-14-53-04',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'savethatmoney-mobilehub-634236437',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_tfXKdxLCi',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '351bpvnk1h7lrqdpsh84fn6560',
}

export default awsmobile;
